### ISSUE TITLE
Ubuntu 18.04 lockscreen notification reads "owncloud"

### ISSUE THREAD

**Issue by torrbox** [nextcloud/client#332] opened 2018-05-18 22:46 UTC
When Nextcloud downloads a new file while my screen is locked on Ubuntu 18.04, the notification on the lockscreen reads "owncloud"

edit: I am using the AppImage.

**Comment by camilasan** [comment] 2018-05-21 18:41
Which version of the client? I believe this has been fixed.

**Comment by torrbox** [comment] 2018-05-22 18:44
Built from Git revision 57bc79 on Nov 20 2017, 09:23:41 using Qt 5.9.2, OpenSSL 1.0.1f 6 Jan 2014

**Comment by juliushaertl** [comment] 2018-05-24 07:56
Closing as a duplicate of #28 

> Already fixed on master by b7fa50b
> This should be fine once a new version is released.

**Closed by juliushaertl** 2018-05-24 07:56 UTC
Labels: needs info
